services:
  _defaults:
    autowire: true
    autoconfigure: true

  Palmyr\CommonUtils\Guzzle\Factory\HandlerStackFactoryInterface:
    class: Palmyr\CommonUtils\Guzzle\Factory\HandlerStackFactory
    arguments:
      - '@logger'

  Palmyr\CommonUtils\Guzzle\Factory\ClientFactoryInterface:
    class: Palmyr\CommonUtils\Guzzle\Factory\ClientFactory
    arguments:
      - '@Palmyr\CommonUtils\Guzzle\Factory\HandlerStackFactoryInterface'

  Palmyr\CommonUtils\IpInfo\Factory\IpInfoServiceFactoryInterface:
    class: Palmyr\CommonUtils\IpInfo\Factory\IpInfoServiceFactory
    arguments:
      - '@Palmyr\CommonUtils\Guzzle\Factory\ClientFactoryInterface'

  Palmyr\CommonUtils\IpInfo\Service\IpInfoServiceInterface:
    class: Palmyr\CommonUtils\IpInfo\Service\IpInfoService
    factory:
      - '@Palmyr\CommonUtils\IpInfo\Factory\IpInfoServiceFactoryInterface'
      - 'createIpInfoService'

  Palmyr\SymfonyCommonUtils\Entity\EventListener\CreatedUpdatedEntityListener:
    class: Palmyr\SymfonyCommonUtils\Entity\EventListener\CreatedUpdatedEntityListener
    tags:
      - name: 'doctrine.event_listener'
        event: 'prePersist'
      - name: 'doctrine.event_listener'
        event: 'preUpdate'